version: 2
jobs:
  build:
    branchs:
      - master
    docker:
      - image: circleci/php:7.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "8a:f4:64:2c:0e:42:87:c5:3c:cf:f4:4d:ae:77:df:45"

      - run:
          name: Start ssh-keyscan
          command: |
            ssh-keyscan ${HOST_NAME_AZURE} >> ~/.ssh/known_hosts

      - deploy:
          name: Start Azure Deploy:Git Clone
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh ${USER_NAME_AZURE}@${HOST_NAME_AZURE} "/bin/bash" < ./clone.sh
            fi
      - deploy:
          name: Start Azure Deploy:Deployer
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh ${USER_NAME_AZURE}@${HOST_NAME_AZURE} "cd /var/www/html/workspace/;composer install;sudo dep deploy develop;"
            fi
      - deploy:
          name: Migrate
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh ${USER_NAME_AZURE}@${HOST_NAME_AZURE} "cd /var/www/html/web/current/;php artisan migrate --force;"
            fi
