# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "8a:f4:64:2c:0e:42:87:c5:3c:cf:f4:4d:ae:77:df:45"

      - run:
          name: Start ssh-keyscan
          command: |
            ssh-keyscan ${HOST_NAME} >> ~/.ssh/known_hosts |
            ssh-keyscan ${HOST_NAME_AZURE} >> ~/.ssh/known_hosts
#      - deploy:
#          name: Start Azure Deploy:Rsync
#          command: |
#            if [ "${CIRCLE_BRANCH}" == "master" ]; then
#              rsync -av --delete --exclude='.git' --exclude='.circleci' ./ ${USER_NAME_AZURE}@${HOST_NAME_AZURE}:/var/www/html/
#            fi
      - deploy:
          name: Start Azure Deploy:Git Clone
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh ${USER_NAME_AZURE}@${HOST_NAME_AZURE} "/bin/bash" < ./clone.sh
            fi
      - deploy:
          name: Start Azure Deploy:Shell
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh ${USER_NAME_AZURE}@${HOST_NAME_AZURE} "cd /var/www/html/web;sudo sh deploy.sh nginx;"
            fi
      - deploy:
          name: Start Azure Deploy:Ansible
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh ${USER_NAME_AZURE}@${HOST_NAME_AZURE} "cd /var/www/html/ansible;sudo ansible-playbook -i inv/hosts test.yml;"
            fi
